FROM nginx:alpine

RUN apk update && \
    apk upgrade && \
    apk add --no-cache libxml2-dev busybox-suid nano

WORKDIR /var/www/html
COPY ./ /var/www/html

COPY docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

## add permissions for nginx user
RUN chown -R nginx:nginx /var/www/html && chmod -R 755 /var/www/html && \
        chown -R nginx:nginx /var/cache/nginx && \
        chown -R nginx:nginx /var/log/nginx && \
        chown -R nginx:nginx /etc/nginx/conf.d
RUN touch /var/run/nginx.pid && \
        chown -R nginx:nginx /var/run/nginx.pid

RUN rm -rf /var/www/.scannerwork

USER nginx